fire:
  - огонёк
moai:
  - каменное лицо
clown face:
  - смайл клоуна
bomb:
  - бомбу
ice cube:
  - куб льда
package:
  - коробку
game die:
  - игральную кость
cofee:
  - чашку чая
  - чашку кофе
  - чашку
butterfly:
  - бабочку
fox:
  - морду лисы
  - морду лисички
  - смайлик лисички

lemon:
  - лимон
  - лимончик
  - лемон    #facepalm
  - лемончик #facepalm
apple:
  - яблоко
  - яблочко
pineapple:
  - ананасик
cheese:
  - сыр

cat:
  - котика
  - кота
  - кошку
dog:
  - собачку
roaster:
  - петуха
parrot:
  - папуга
  - попугая
  - попугайчика
rabbit:
  - кролика
  - крольчатину
bee:
  - пчелу


pepe the frog:
  - лягушку Пепе
  - лягушонка Пепе
  - Пепе
anime girl:
  - аниме девчонку
  - аниме девочку
dancing anime character:
  - танцующего аниме персонажа
banana:
  - танцующий банан
  - флексящий банан
toilet:
  - туалет
  - вращающийся туалет
  - поворачивающийся туалет
sewing machine:
  - швейную машину
  - машинку для шитья
wrench:
  - гаечный ключ
hammer:
  - молоток
cpu:
  - процессор
gpu:
  - видеокарту

# Логотипы
lolz:
  - лого лолзтима
  - лого лолза
  - лого этого форума
steam:
  - стим
  - лого стима
discord:
  - discord
  - иконку дискорда
  - лого дискорда
bitcoin:
  - bitcoin
  - лого биткоина
yoomoney:
  - yoomoney
  - лого юмани
webmoney:
  - webmoney
  - лого webmoney
qiwi:
  - qiwi
  - лого киви
sberbank:
  - сбер
  - лого сбера
  - лого сбербанка
telegram:
  - telegram
  - иконку телеги
  - телеграм
instagram:
  - instagram
  - иконку instagram
  - иконку инсты
  - лого инсты
  - лого инстаграма
vkontakte:
  - лого vkontakte
  - vk
youtube:
  - иконку ютубчика
  - ютубчик

# Флаги
russia:
  - флаг России
  - флаг Российской Федерации
  - флаг РФ
usa:
  - флаг США
  - флаг Соединённых Штатов Америки
japan:
  - флаг Японии
belarus:
  - флаг Белорусии
  - флаг РБ
ukraine:
  - флаг Украины
